import type { Faculty, KnownSource, User } from '$lib/types'

export const users: User[] = [
  {
    id: '1',
    role: 'student',
    firstInterest: 'Faculty of Engineering',
    secondInterest: 'Faculty of Science',
    thirdInterest: 'Faculty of Medicine',
    registeredAt: '2025-03-12T00:00:00Z',
    lastEntered: '2025-03-14T00:00:00Z',
    province: 'กรุงเทพมหานคร',
    selectedSources: ['Facebook', 'Instagram'],
    status: 'ม.ต้น',
  },
  {
    id: '2',
    role: 'student',
    firstInterest: 'Faculty of Engineering',
    secondInterest: 'Faculty of Science',
    thirdInterest: 'Faculty of Medicine',
    registeredAt: '2025-03-14T00:00:00Z',
    lastEntered: '2025-03-14T00:00:00Z',
    province: 'เชียงใหม่',
    selectedSources: ['Facebook', 'Instagram'],
    status: 'ม.ต้น',
  },
  {
    id: '3',
    role: 'student',
    firstInterest: 'Faculty of Engineering',
    secondInterest: 'Faculty of Science',
    thirdInterest: 'Faculty of Medicine',
    registeredAt: '2025-03-14T00:00:00Z',
    lastEntered: '2025-03-14T00:00:00Z',
    province: 'เชียงราย',
    selectedSources: ['Facebook', 'Instagram'],
    status: 'ม.ต้น',
  },
  {
    id: '4',
    role: 'student',
    firstInterest: 'Faculty of Engineering',
    secondInterest: 'Faculty of Science',
    thirdInterest: 'Faculty of Medicine',
    registeredAt: '2025-03-14T00:00:00Z',
    lastEntered: '2025-03-14T00:00:00Z',
    province: 'กรุงเทพมหานคร',
    selectedSources: ['Facebook', 'Instagram'],
    status: 'ม.ต้น',
  },
  {
    id: '5',
    role: 'student',
    firstInterest: 'Faculty of Engineering',
    secondInterest: 'Faculty of Science',
    thirdInterest: 'Faculty of Medicine',
    registeredAt: '2025-03-14T00:00:00Z',
    lastEntered: '2025-03-14T00:00:00Z',
    province: 'กรุงเทพมหานคร',
    selectedSources: ['Facebook', 'Instagram'],
    status: 'ม.ต้น',
  },
  {
    id: '6',
    role: 'student',
    firstInterest: 'Faculty of Engineering',
    secondInterest: 'Faculty of Science',
    thirdInterest: 'Faculty of Medicine',
    registeredAt: '2025-03-14T00:00:00Z',
    lastEntered: '2025-03-14T00:00:00Z',
    province: 'นครปฐม',
    selectedSources: ['Facebook', 'Instagram'],
    status: 'ม.ต้น',
  },
  {
    id: '7',
    role: 'student',
    firstInterest: 'Faculty of Engineering',
    secondInterest: 'Faculty of Science',
    thirdInterest: 'Faculty of Medicine',
    registeredAt: '2025-03-14T00:00:00Z',
    lastEntered: '2025-03-14T00:00:00Z',
    province: 'กรุงเทพมหานคร',
    selectedSources: ['Facebook', 'Instagram'],
    status: 'ม.ต้น',
  },
  {
    id: '8',
    role: 'student',
    firstInterest: 'Faculty of Engineering',
    secondInterest: 'Faculty of Science',
    thirdInterest: 'Faculty of Medicine',
    registeredAt: '2025-03-14T00:00:00Z',
    lastEntered: '2025-03-14T00:00:00Z',
    province: ' กรุงเทพมหานคร',
    selectedSources: ['Facebook', 'Instagram'],
    status: 'ม.ต้น',
  },
  {
    id: '9',
    role: 'student',
    firstInterest: 'Faculty of Engineering',
    secondInterest: 'Faculty of Science',
    thirdInterest: 'Faculty of Medicine',
    registeredAt: '2025-03-14T00:00:00Z',
    lastEntered: '2025-03-14T00:00:00Z',
    province: 'กรุงเทพมหานคร',
    selectedSources: ['Facebook', 'Instagram'],
    status: 'ม.ต้น',
  },
  {
    id: '10',
    role: 'student',
    firstInterest: 'Faculty of Engineering',
    secondInterest: 'Faculty of Science',
    thirdInterest: 'Faculty of Medicine',
    registeredAt: '2025-03-14T00:00:00Z',
    lastEntered: '2025-03-14T00:00:00Z',
    province: 'กรุงเทพมหานคร',
    selectedSources: ['Facebook', 'Instagram'],
    status: 'ม.ปลาย',
  },
  {
    id: '11',
    role: 'student',
    firstInterest: 'Faculty of Engineering',
    secondInterest: 'Faculty of Science',
    thirdInterest: 'Faculty of Medicine',
    registeredAt: '2025-03-14T00:00:00Z',
    lastEntered: '2025-03-14T00:00:00Z',
    province: 'กรุงเทพมหานคร',
    selectedSources: ['Facebook', 'Instagram'],
    status: 'ม.ปลาย',
  },
  {
    id: '12',
    role: 'student',
    firstInterest: 'Faculty of Engineering',
    secondInterest: 'Faculty of Science',
    thirdInterest: 'Faculty of Medicine',
    registeredAt: '2025-03-14T00:00:00Z',
    lastEntered: '2025-03-14T00:00:00Z',
    province: 'กรุงเทพมหานคร',
    selectedSources: ['Facebook', 'Instagram'],
    status: 'ม.ปลาย',
  },
  {
    id: '13',
    role: 'student',
    firstInterest: 'Faculty of Engineering',
    secondInterest: 'Faculty of Science',
    thirdInterest: 'Faculty of Medicine',
    registeredAt: '2025-03-14T00:00:00Z',
    lastEntered: '2025-03-14T00:00:00Z',
    province: 'กรุงเทพมหานคร',
    selectedSources: ['Facebook', 'Instagram'],
    status: 'ม.ปลาย',
  },
  {
    id: '14',
    role: 'student',
    firstInterest: 'Faculty of Engineering',
    secondInterest: 'Faculty of Science',
    thirdInterest: 'Faculty of Medicine',
    registeredAt: '2025-03-14T00:00:00Z',
    lastEntered: '2025-03-14T00:00:00Z',
    province: 'กรุงเทพมหานคร',
    selectedSources: ['Facebook', 'Instagram'],
    status: 'ม.ปลาย',
  },
  {
    id: '15',
    role: 'student',
    firstInterest: 'Faculty of Engineering',
    secondInterest: 'Faculty of Science',
    thirdInterest: 'Faculty of Medicine',
    registeredAt: '2025-03-15T00:00:00Z',
    lastEntered: '2025-03-15T00:00:00Z',
    province: 'กรุงเทพมหานคร',
    selectedSources: ['Facebook', 'Instagram'],
    status: 'ม.ปลาย',
  },
  {
    id: '16',
    role: 'student',
    firstInterest: 'Faculty of Engineering',
    secondInterest: 'Faculty of Science',
    thirdInterest: 'Faculty of Medicine',
    registeredAt: '2025-03-15T00:00:00Z',
    lastEntered: '2025-03-15T00:00:00Z',
    province: 'กรุงเทพมหานคร',
    selectedSources: ['Facebook', 'Instagram'],
    status: 'ผู้ปกครอง',
  }
]

export const interestedFaculties: Faculty[] = [
  {
    "faculty": "ศิลปะ",
    "first_interest": 6036,
    "second_interest": 6060,
    "third_interest": 0
  },
  {
    "faculty": "แพทย์",
    "first_interest": 5949,
    "second_interest": 5963,
    "third_interest": 0
  },
  {
    "faculty": "วิศวะ",
    "first_interest": 6102,
    "second_interest": 5867,
    "third_interest": 0
  },
  {
    "faculty": "นิเทศศาสตร์",
    "first_interest": 0,
    "second_interest": 6065,
    "third_interest": 0
  },
  {
    "faculty": "ดนตรี",
    "first_interest": 0,
    "second_interest": 0,
    "third_interest": 0
  },
  {
    "faculty": "สถาปัตย์",
    "first_interest": 0,
    "second_interest": 6045,
    "third_interest": 0
  },
  {
    "faculty": "วิทยาศาสตร์",
    "first_interest": 5981,
    "second_interest": 0,
    "third_interest": 0
  },
  {
    "faculty": "เกษตร",
    "first_interest": 0,
    "second_interest": 0,
    "third_interest": 0
  },
  {
    "faculty": "ธุรกิจ",
    "first_interest": 5932,
    "second_interest": 0,
    "third_interest": 0
  }
]

export const mediaSources: KnownSource[] = [
  {
    "source": "facebook",
    "count": 30000
  },
  {
    "source": "website",
    "count": 30000
  }
]
