import type { StudentTransaction, User } from '$lib/types'

export const users: User[] = [
  {
    id: '1',
    role: 'student',
    firstInterest: 'Faculty of Engineering',
    secondInterest: 'Faculty of Science',
    thirdInterest: 'Faculty of Medicine',
    registeredAt: '2021-09-01T00:00:00Z',
    lastEntered: '2021-09-01T00:00:00Z',
    province: 'กรุงเทพมหานคร',
    selectedSources: ['Facebook', 'Instagram'],
    status: 'ม.ต้น',
  },
  {
    id: '2',
    role: 'student',
    firstInterest: 'Faculty of Engineering',
    secondInterest: 'Faculty of Science',
    thirdInterest: 'Faculty of Medicine',
    registeredAt: '2021-09-01T00:00:00Z',
    lastEntered: '2021-09-01T00:00:00Z',
    province: 'เชียงใหม่',
    selectedSources: ['Facebook', 'Instagram'],
    status: 'ม.ต้น',
  },
  {
    id: '3',
    role: 'student',
    firstInterest: 'Faculty of Engineering',
    secondInterest: 'Faculty of Science',
    thirdInterest: 'Faculty of Medicine',
    registeredAt: '2021-09-01T00:00:00Z',
    lastEntered: '2021-09-01T00:00:00Z',
    province: 'เชียงราย',
    selectedSources: ['Facebook', 'Instagram'],
    status: 'ม.ต้น',
  },
  {
    id: '4',
    role: 'student',
    firstInterest: 'Faculty of Engineering',
    secondInterest: 'Faculty of Science',
    thirdInterest: 'Faculty of Medicine',
    registeredAt: '2021-09-01T00:00:00Z',
    lastEntered: '2021-09-01T00:00:00Z',
    province: 'กรุงเทพมหานคร',
    selectedSources: ['Facebook', 'Instagram'],
    status: 'ม.ต้น',
  },
  {
    id: '5',
    role: 'student',
    firstInterest: 'Faculty of Engineering',
    secondInterest: 'Faculty of Science',
    thirdInterest: 'Faculty of Medicine',
    registeredAt: '2021-09-01T00:00:00Z',
    lastEntered: '2021-09-01T00:00:00Z',
    province: 'กรุงเทพมหานคร',
    selectedSources: ['Facebook', 'Instagram'],
    status: 'ม.ต้น',
  },
  {
    id: '6',
    role: 'student',
    firstInterest: 'Faculty of Engineering',
    secondInterest: 'Faculty of Science',
    thirdInterest: 'Faculty of Medicine',
    registeredAt: '2021-09-01T00:00:00Z',
    lastEntered: '2021-09-01T00:00:00Z',
    province: 'นครปฐม',
    selectedSources: ['Facebook', 'Instagram'],
    status: 'ม.ต้น',
  },
  {
    id: '7',
    role: 'student',
    firstInterest: 'Faculty of Engineering',
    secondInterest: 'Faculty of Science',
    thirdInterest: 'Faculty of Medicine',
    registeredAt: '2021-09-01T00:00:00Z',
    lastEntered: '2021-09-01T00:00:00Z',
    province: 'กรุงเทพมหานคร',
    selectedSources: ['Facebook', 'Instagram'],
    status: 'ม.ต้น',
  },
  {
    id: '8',
    role: 'student',
    firstInterest: 'Faculty of Engineering',
    secondInterest: 'Faculty of Science',
    thirdInterest: 'Faculty of Medicine',
    registeredAt: '2021-09-01T00:00:00Z',
    lastEntered: '2021-09-01T00:00:00Z',
    province: ' กรุงเทพมหานคร',
    selectedSources: ['Facebook', 'Instagram'],
    status: 'ม.ต้น',
  },
  {
    id: '9',
    role: 'student',
    firstInterest: 'Faculty of Engineering',
    secondInterest: 'Faculty of Science',
    thirdInterest: 'Faculty of Medicine',
    registeredAt: '2021-09-01T00:00:00Z',
    lastEntered: '2021-09-01T00:00:00Z',
    province: 'กรุงเทพมหานคร',
    selectedSources: ['Facebook', 'Instagram'],
    status: 'ม.ต้น',
  },
  {
    id: '10',
    role: 'student',
    firstInterest: 'Faculty of Engineering',
    secondInterest: 'Faculty of Science',
    thirdInterest: 'Faculty of Medicine',
    registeredAt: '2021-09-01T00:00:00Z',
    lastEntered: '2021-09-01T00:00:00Z',
    province: 'กรุงเทพมหานคร',
    selectedSources: ['Facebook', 'Instagram'],
    status: 'ม.ปลาย',
  },
  {
    id: '11',
    role: 'student',
    firstInterest: 'Faculty of Engineering',
    secondInterest: 'Faculty of Science',
    thirdInterest: 'Faculty of Medicine',
    registeredAt: '2021-09-01T00:00:00Z',
    lastEntered: '2021-09-01T00:00:00Z',
    province: 'กรุงเทพมหานคร',
    selectedSources: ['Facebook', 'Instagram'],
    status: 'ม.ปลาย',
  },
  {
    id: '12',
    role: 'student',
    firstInterest: 'Faculty of Engineering',
    secondInterest: 'Faculty of Science',
    thirdInterest: 'Faculty of Medicine',
    registeredAt: '2021-09-01T00:00:00Z',
    lastEntered: '2021-09-01T00:00:00Z',
    province: 'กรุงเทพมหานคร',
    selectedSources: ['Facebook', 'Instagram'],
    status: 'ม.ปลาย',
  },
  {
    id: '13',
    role: 'student',
    firstInterest: 'Faculty of Engineering',
    secondInterest: 'Faculty of Science',
    thirdInterest: 'Faculty of Medicine',
    registeredAt: '2021-09-01T00:00:00Z',
    lastEntered: '2021-09-01T00:00:00Z',
    province: 'กรุงเทพมหานคร',
    selectedSources: ['Facebook', 'Instagram'],
    status: 'ม.ปลาย',
  },
  {
    id: '14',
    role: 'student',
    firstInterest: 'Faculty of Engineering',
    secondInterest: 'Faculty of Science',
    thirdInterest: 'Faculty of Medicine',
    registeredAt: '2021-09-01T00:00:00Z',
    lastEntered: '2021-09-01T00:00:00Z',
    province: 'กรุงเทพมหานคร',
    selectedSources: ['Facebook', 'Instagram'],
    status: 'ม.ปลาย',
  },
  {
    id: '15',
    role: 'student',
    firstInterest: 'Faculty of Engineering',
    secondInterest: 'Faculty of Science',
    thirdInterest: 'Faculty of Medicine',
    registeredAt: '2021-09-01T00:00:00Z',
    lastEntered: '2021-09-01T00:00:00Z',
    province: 'กรุงเทพมหานคร',
    selectedSources: ['Facebook', 'Instagram'],
    status: 'ม.ปลาย',
  },
  {
    id: '16',
    role: 'student',
    firstInterest: 'Faculty of Engineering',
    secondInterest: 'Faculty of Science',
    thirdInterest: 'Faculty of Medicine',
    registeredAt: '2021-09-01T00:00:00Z',
    lastEntered: '2021-09-01T00:00:00Z',
    province: 'กรุงเทพมหานคร',
    selectedSources: ['Facebook', 'Instagram'],
    status: 'ผู้ปกครอง',
  }
]
